export enum ErrorCode {
  MANIFEST_MISSING_FIELD = 'MANIFEST_MISSING_FIELD',
  MANIFEST_INVALID_FORMAT = 'MANIFEST_INVALID_FORMAT',
  MANIFEST_INVALID_CREDENTIAL = 'MANIFEST_INVALID_CREDENTIAL',
  SIGNATURE_INVALID = 'SIGNATURE_INVALID',
  SYSTEM_SECURITY_BREACH = 'SYSTEM_SECURITY_BREACH',
  RESPONSE_CONTAINED_SENSITIVE_DATA = 'RESPONSE_CONTAINED_SENSITIVE_DATA',
  MALICIOUS_CONTENT_DETECTED = 'MALICIOUS_CONTENT_DETECTED',
  SECURITY_VIOLATION = 'SECURITY_VIOLATION'
}
