export const MANIFEST_INVALID_FIELDS = 'MANIFEST_INVALID_FIELDS'
export const MANIFEST_EXPIRED = 'MANIFEST_EXPIRED'
export const SIGNATURE_INVALID = 'SIGNATURE_INVALID'
export const KEY_INVALID = 'KEY_INVALID'
